Repository javafxports/openjdk-jfx, pull requests merged in 2018-11, with the labels that each got.

#267 Update README.md to fix typo and add pointers to HG repo, JBS
  .github/CONTRIBUTING.md
  .github/README.md
Labels: documentation

#271 JDK-8211304: [macOS] Crash on focus loss from dialog on macOS 10.14 Mojave
  modules/javafx.graphics/src/main/native-glass/mac/GlassTouches.m
Labels: bug

#276 JDK-8213619 Initialized additional environment variables.
  tools/scripts/build.ps1
Labels: housekeeping

#281 JDK-8213541: WebView does not handle HTTP response without ContentType
  modules/javafx.web/src/main/native/Source/WebCore/platform/network/java/URLLoader.cpp
Labels: bug

#300 Improvements in javafx cache for native files (JDK-8214397)
  modules/javafx.graphics/src/main/java/com/sun/glass/utils/NativeLibLoader.java
Labels: bug

#293 JDK-8214069 : (JavaFX) Default to xdg-open for document opening on UNIX
  modules/javafx.graphics/src/main/java/com/sun/javafx/application/HostServicesDelegate.java
Labels: enhancement
