Repository javafxports/openjdk-jfx, pull requests merged in 2018-08, with the labels that each got.

#154 Check white-space rules as part of Travis CI build
  .ci/script.sh
  .github/pr-check-whitespace.sh
  .github/pr-list-files.sh
Labels: enhancement

#158 Change .ci/* scripts to be non-executable
  .ci/before_install.sh
  .ci/script.sh
  .github/pr-check-whitespace.sh
  .travis.yml
Labels: bug

#153 Add a powershell script for Windows dev, use on Appveyor.
  appveyor.yml
  tools/scripts/build.ps1
Labels: enhancement

#147 JDK-8207328 Fix Stylesheet Javadocs
  modules/javafx.graphics/src/main/java/javafx/css/Stylesheet.java
Labels: documentation, enhancement

#185 JDK-8210219: GlassClipboard.cpp fails to compile with newer versions of VS2017
  modules/javafx.graphics/src/main/native-glass/win/GlassClipboard.cpp
Labels: bug

#189 Run checkWhiteSpace without -v option
  .github/pr-check-whitespace.sh
  .github/pr-list-files.sh
Labels: bug
