Repository javafxports/openjdk-jfx, pull requests merged in 2018-09, with the labels that each got.

#172 JDK-8209969: Monocle setBounds issue (width/height mixed)
  modules/javafx.graphics/src/main/java/com/sun/glass/ui/monocle/MonocleWindow.java
Labels: bug

#197 Fix pr-list-files.sh script so renamed files are checked for white-space erorrs
  .github/pr-list-files.sh
Labels: bug

#198 only publish Swing artifacts if we are going to build Swing
  build.gradle
Labels: bug

#51 JDK-8148129: Implement Accelerated composition for WebView
  modules/javafx.graphics/src/main/java/com/sun/prism/Graphics.java
  modules/javafx.graphics/src/main/java/com/sun/prism/d3d/D3DContext.java
  modules/javafx.graphics/src/main/java/com/sun/prism/es2/ES2Context.java
  modules/javafx.graphics/src/main/java/com/sun/prism/impl/BaseContext.java
  modules/javafx.graphics/src/main/java/com/sun/prism/impl/BaseGraphics.java
  modules/javafx.graphics/src/main/java/com/sun/prism/impl/ps/BaseShaderContext.java
  modules/javafx.graphics/src/main/java/com/sun/prism/j2d/J2DPrismGraphics.java
  modules/javafx.graphics/src/main/java/com/sun/prism/sw/SWGraphics.java
  modules/javafx.web/src/main/java/com/sun/javafx/webkit/prism/WCBufferedContext.java
  modules/javafx.web/src/main/java/com/sun/javafx/webkit/prism/WCGraphicsPrismContext.java
  modules/javafx.web/src/main/java/com/sun/javafx/webkit/prism/WCPageBackBufferImpl.java
  modules/javafx.web/src/main/java/com/sun/webkit/WebPage.java
  modules/javafx.web/src/main/java/com/sun/webkit/graphics/GraphicsDecoder.java
  modules/javafx.web/src/main/java/com/sun/webkit/graphics/WCCamera.java
  modules/javafx.web/src/main/java/com/sun/webkit/graphics/WCGraphicsContext.java
  modules/javafx.web/src/main/java/com/sun/webkit/graphics/WCTransform.java
  modules/javafx.web/src/main/java/com/sun/webkit/perf/WCGraphicsPerfLogger.java
  modules/javafx.web/src/main/native/Source/WebCore/PlatformJava.cmake
  modules/javafx.web/src/main/native/Source/WebCore/SourcesPlatformJava.txt
  modules/javafx.web/src/main/native/Source/WebCore/platform/graphics/java/GraphicsContextJava.cpp
  modules/javafx.web/src/main/native/Source/WebCore/platform/graphics/java/PlatformContextJava.h
  modules/javafx.web/src/main/native/Source/WebCore/platform/graphics/texmap/BitmapTextureJava.cpp
  modules/javafx.web/src/main/native/Source/WebCore/platform/graphics/texmap/BitmapTextureJava.h
  modules/javafx.web/src/main/native/Source/WebCore/platform/graphics/texmap/BitmapTexturePool.cpp
  modules/javafx.web/src/main/native/Source/WebCore/platform/graphics/texmap/BitmapTexturePool.h
  modules/javafx.web/src/main/native/Source/WebCore/platform/graphics/texmap/TextureMapper.h
  modules/javafx.web/src/main/native/Source/WebCore/platform/graphics/texmap/TextureMapperBackingStore.cpp
  modules/javafx.web/src/main/native/Source/WebCore/platform/graphics/texmap/TextureMapperJava.cpp
  modules/javafx.web/src/main/native/Source/WebCore/platform/graphics/texmap/TextureMapperJava.h
  modules/javafx.web/src/main/native/Source/WebCore/platform/graphics/texmap/TextureMapperLayer.cpp
  modules/javafx.web/src/main/native/Source/WebCore/platform/graphics/texmap/TextureMapperLayer.h
  modules/javafx.web/src/main/native/Source/WebCore/platform/java/ChromeClientJava.cpp
  modules/javafx.web/src/main/native/Source/WebCore/platform/java/ChromeClientJava.h
  modules/javafx.web/src/main/native/Source/WebCore/platform/java/WebPage.cpp
  modules/javafx.web/src/main/native/Source/WebCore/platform/java/WebPage.h
  modules/javafx.web/src/main/native/Source/WebCore/rendering/RenderLayerCompositor.cpp
Labels: enhancement

#200 JDK-8210218: WebKit build fails with newer versions of VS 2017
  modules/javafx.web/src/main/native/Source/WTF/wtf/Variant.h
Labels: bug, compiler-issue

#201 JDK-8210691: Deliver release notes for JavaFX 11
  doc-files/release-notes-11.md
Labels: documentation

#202 JDK-8210791: Update release notes for JavaFX 11
  doc-files/release-notes-11.md
Labels: documentation

#174 JDK-8209966: Update minimum boot JDK to 11
  build.gradle
  build.properties
Labels: enhancement

#208 JDK-8210093: Build FX class files with -source 11 and -target 11
  build.gradle
Labels: enhancement

#207 JDK-8210092: Remove old javafx.swing implementation
  build.gradle
  dependencies/java.desktop/module-info.java.extra
  modules/javafx.swing/.classpath
  modules/javafx.swing/src/main/java/com/sun/javafx/embed/swing/InteropFactory.java
  modules/javafx.swing/src/main/java/com/sun/javafx/embed/swing/oldimpl/FXDnDInteropO.java
  modules/javafx.swing/src/main/java/com/sun/javafx/embed/swing/oldimpl/JFXPanelInteropO.java
  modules/javafx.swing/src/main/java/com/sun/javafx/embed/swing/oldimpl/SwingFXUtilsImplInteropO.java
  modules/javafx.swing/src/main/java/com/sun/javafx/embed/swing/oldimpl/SwingNodeInteropO.java
  modules/javafx.swing/src/main/java/module-info.java
  modules/javafx.swing/src/main/module-info/module-info.java
Labels: bug
