Repository javafxports/openjdk-jfx, pull requests merged in 2018-12, with the labels that each got.

#283 JDK-8211307: Add prefix to build tools paths
  build.gradle
  buildSrc/linux.gradle
  buildSrc/mac.gradle
  buildSrc/win.gradle
  modules/javafx.web/src/main/native/Source/WebCore/PlatformJava.cmake
  modules/javafx.web/src/main/native/Source/WebCore/WebCoreMacros.cmake
  modules/javafx.web/src/main/native/Source/WebCore/bindings/scripts/generate-bindings-all.pl
  modules/javafx.web/src/main/native/Source/WebCore/bindings/scripts/generate-bindings.pl
  modules/javafx.web/src/main/native/Tools/Scripts/webkitdirs.pm
Labels: build

#215 JDK-8207369 Add more robot tests.
  tests/system/src/test/java/test/robot/javafx/scene/RobotTest.java
Labels: enhancement

#163 JDK-8207942: Add protected API to VirtualFlow and other related classes for sublclassing
  modules/javafx.controls/src/main/java/com/sun/javafx/scene/control/behavior/TableViewBehaviorBase.java
  modules/javafx.controls/src/main/java/javafx/scene/control/skin/ListViewSkin.java
  modules/javafx.controls/src/main/java/javafx/scene/control/skin/TableColumnHeader.java
  modules/javafx.controls/src/main/java/javafx/scene/control/skin/TableHeaderRow.java
  modules/javafx.controls/src/main/java/javafx/scene/control/skin/TableViewSkin.java
  modules/javafx.controls/src/main/java/javafx/scene/control/skin/TableViewSkinBase.java
  modules/javafx.controls/src/main/java/javafx/scene/control/skin/TreeTableViewSkin.java
  modules/javafx.controls/src/main/java/javafx/scene/control/skin/TreeViewSkin.java
  modules/javafx.controls/src/main/java/javafx/scene/control/skin/VirtualFlow.java
  modules/javafx.controls/src/shims/java/javafx/scene/control/skin/VirtualFlowShim.java
  modules/javafx.controls/src/test/java/test/javafx/scene/control/skin/VirtualFlowSubClassTest.java
Labels: enhancement

#312 8167068: Fixed undefined pixcoord error starting javafx
  modules/javafx.graphics/src/jslc/java/com/sun/scenario/effect/compiler/backend/hw/ES2Backend.java
  modules/javafx.graphics/src/jslc/java/com/sun/scenario/effect/compiler/backend/hw/GLSLBackend.java
  modules/javafx.graphics/src/jslc/java/com/sun/scenario/effect/compiler/backend/hw/SLBackend.java
Labels: bug

#328 Allow for skipping Cygwin installation when using build.ps1 (JDK-8215629)
  build.gradle
  tools/scripts/build.ps1
Labels: build, enhancement
