Repository javafxports/openjdk-jfx, pull requests merged in 2018-07, with the labels that each got.

#124 Fix CONTRIBUTING.md to indicate that PRs should use the develop branch
  .github/CONTRIBUTING.md
Labels: bug, housekeeping

#36 JDK-8203409: FX Robot API
  apps/tests/HelloTest/src/hellotest/RemoveFocusedControl.java
  apps/tests/Robot/src/robottest/RobotBuilder.java
  buildSrc/addExports
  modules/javafx.graphics/src/main/java/com/sun/glass/ui/Application.java
  modules/javafx.graphics/src/main/java/com/sun/glass/ui/GlassRobot.java
  modules/javafx.graphics/src/main/java/com/sun/glass/ui/Robot.java
  modules/javafx.graphics/src/main/java/com/sun/glass/ui/gtk/GtkApplication.java
  modules/javafx.graphics/src/main/java/com/sun/glass/ui/gtk/GtkRobot.java
  modules/javafx.graphics/src/main/java/com/sun/glass/ui/ios/IosApplication.java
  modules/javafx.graphics/src/main/java/com/sun/glass/ui/ios/IosRobot.java
  modules/javafx.graphics/src/main/java/com/sun/glass/ui/mac/MacApplication.java
  modules/javafx.graphics/src/main/java/com/sun/glass/ui/mac/MacRobot.java
  modules/javafx.graphics/src/main/java/com/sun/glass/ui/monocle/MonocleApplication.java
  modules/javafx.graphics/src/main/java/com/sun/glass/ui/monocle/MonocleRobot.java
  modules/javafx.graphics/src/main/java/com/sun/glass/ui/win/WinApplication.java
  modules/javafx.graphics/src/main/java/com/sun/glass/ui/win/WinRobot.java
  modules/javafx.graphics/src/main/java/com/sun/javafx/tk/DummyToolkit.java
  modules/javafx.graphics/src/main/java/com/sun/javafx/tk/Toolkit.java
  modules/javafx.graphics/src/main/java/com/sun/javafx/tk/quantum/QuantumToolkit.java
  modules/javafx.graphics/src/main/java/javafx/scene/robot/Robot.java
  modules/javafx.graphics/src/main/java/javafx/scene/robot/package.html
  modules/javafx.graphics/src/main/java/module-info.java
  modules/javafx.graphics/src/main/native-glass/gtk/GlassRobot.cpp
  modules/javafx.graphics/src/main/native-glass/mac/GlassRobot.m
  modules/javafx.graphics/src/main/native-glass/win/Robot.cpp
  modules/javafx.graphics/src/test/addExports
  modules/javafx.graphics/src/test/java/test/com/sun/javafx/pgstub/StubToolkit.java
  tests/system/src/test/java/test/robot/com/sun/glass/ui/monocle/ModalDialogTest.java
  tests/system/src/test/java/test/robot/com/sun/glass/ui/monocle/RobotTest.java
  tests/system/src/test/java/test/robot/com/sun/glass/ui/monocle/TestApplication.java
  tests/system/src/test/java/test/robot/helloworld/CustomSecurityManagerTest.java
  tests/system/src/test/java/test/robot/javafx/embed/swing/RT30650GUI.java
  tests/system/src/test/java/test/robot/javafx/embed/swing/SwingNodeBase.java
  tests/system/src/test/java/test/robot/javafx/scene/AfterModalClosedTest.java
  tests/system/src/test/java/test/robot/javafx/scene/MouseLocationOnScreenTest.java
  tests/system/src/test/java/test/robot/javafx/scene/RobotTest.java
  tests/system/src/test/java/test/robot/javafx/scene/SceneChangeEventsTest.java
  tests/system/src/test/java/test/robot/javafx/scene/TabContextMenuCloseButtonTest.java
  tests/system/src/test/java/test/robot/javafx/scene/TabPaneDragPolicyTest.java
  tests/system/src/test/java/test/robot/javafx/scene/tableview/TableViewResizeColumnToFitContentTest.java
  tests/system/src/test/java/test/robot/javafx/scene/treetableview/TreeTableViewResizeColumnToFitContentTest.java
  tests/system/src/test/java/test/robot/javafx/web/TooltipFXTest.java
  tests/system/src/test/java/test/robot/testharness/VisualTestBase.java
Labels: enhancement

#83 Build standalone modules (jars) to be uploaded to remote repositories
  build.gradle
  javafx.pom
  modules/javafx.graphics/src/main/java/com/sun/glass/utils/NativeLibLoader.java
  modules/javafx.graphics/src/main/java/com/sun/javafx/tk/Toolkit.java
  modules/javafx.media/src/main/java/com/sun/media/jfxmediaimpl/NativeMediaManager.java
Labels: enhancement

#117 JDK-8147476 : Rendering issues with MathML token elements.
  modules/javafx.web/src/main/java/com/sun/javafx/webkit/prism/WCFontImpl.java
  modules/javafx.web/src/main/java/com/sun/webkit/graphics/WCFont.java
  modules/javafx.web/src/main/java/com/sun/webkit/perf/WCFontPerfLogger.java
  modules/javafx.web/src/main/native/Source/WebCore/platform/graphics/java/FontJava.cpp
  modules/javafx.web/src/test/java/test/javafx/scene/web/MathMLRenderTest.java
Labels: bug

#136 JDK-8207015: jlink javafx.graphics on Windows fails: PluginException: Duplicate resources
  build.gradle
  buildSrc/win.gradle
Labels: bug

#143 correct library name
  modules/javafx.graphics/src/main/java/com/sun/glass/utils/NativeLibLoader.java
Labels: bug
