Repository javafxports/openjdk-jfx, pull requests merged in 2019-01, with the labels that each got.

#173 JDK-8090930: Support mouse forward/back buttons.
  modules/javafx.controls/src/test/java/test/com/sun/javafx/scene/control/infrastructure/MouseEventFirer.java
  modules/javafx.graphics/src/main/java/com/sun/glass/events/KeyEvent.java
  modules/javafx.graphics/src/main/java/com/sun/glass/events/MouseEvent.java
  modules/javafx.graphics/src/main/java/com/sun/glass/ui/GlassRobot.java
  modules/javafx.graphics/src/main/java/com/sun/glass/ui/monocle/LinuxMouseProcessor.java
  modules/javafx.graphics/src/main/java/com/sun/glass/ui/monocle/MonocleRobot.java
  modules/javafx.graphics/src/main/java/com/sun/glass/ui/monocle/MouseState.java
  modules/javafx.graphics/src/main/java/com/sun/glass/ui/monocle/VNCScreen.java
  modules/javafx.graphics/src/main/java/com/sun/glass/ui/monocle/X.java
  modules/javafx.graphics/src/main/java/com/sun/glass/ui/monocle/X11InputDeviceRegistry.java
  modules/javafx.graphics/src/main/java/com/sun/javafx/embed/AbstractEvents.java
  modules/javafx.graphics/src/main/java/com/sun/javafx/embed/EmbeddedSceneInterface.java
  modules/javafx.graphics/src/main/java/com/sun/javafx/tk/TKSceneListener.java
  modules/javafx.graphics/src/main/java/com/sun/javafx/tk/quantum/EmbeddedScene.java
  modules/javafx.graphics/src/main/java/com/sun/javafx/tk/quantum/GlassEventUtils.java
  modules/javafx.graphics/src/main/java/com/sun/javafx/tk/quantum/GlassViewEventHandler.java
  modules/javafx.graphics/src/main/java/javafx/scene/Scene.java
  modules/javafx.graphics/src/main/java/javafx/scene/input/MouseButton.java
  modules/javafx.graphics/src/main/java/javafx/scene/input/MouseDragEvent.java
  modules/javafx.graphics/src/main/java/javafx/scene/input/MouseEvent.java
  modules/javafx.graphics/src/main/native-glass/gtk/GlassRobot.cpp
  modules/javafx.graphics/src/main/native-glass/gtk/glass_key.cpp
  modules/javafx.graphics/src/main/native-glass/gtk/glass_window.cpp
  modules/javafx.graphics/src/main/native-glass/ios/GlassViewDelegate.m
  modules/javafx.graphics/src/main/native-glass/mac/GlassKey.m
  modules/javafx.graphics/src/main/native-glass/mac/GlassViewDelegate.m
  modules/javafx.graphics/src/main/native-glass/win/FullScreenWindow.cpp
  modules/javafx.graphics/src/main/native-glass/win/GlassDnD.cpp
  modules/javafx.graphics/src/main/native-glass/win/GlassWindow.cpp
  modules/javafx.graphics/src/main/native-glass/win/Robot.cpp
  modules/javafx.graphics/src/main/native-glass/win/Utils.cpp
  modules/javafx.graphics/src/main/native-glass/win/ViewContainer.cpp
  modules/javafx.graphics/src/test/java/test/javafx/scene/input/MouseDragEventTest.java
  modules/javafx.graphics/src/test/java/test/javafx/scene/input/MouseEventTest.java
  modules/javafx.swing/src/main/java/com/sun/javafx/embed/swing/SwingEvents.java
  modules/javafx.swing/src/main/java/javafx/embed/swing/JFXPanel.java
  modules/javafx.swt/src/main/java/javafx/embed/swt/FXCanvas.java
  modules/javafx.swt/src/main/java/javafx/embed/swt/SWTEvents.java
  tests/manual/swt/FXCanvasMouseButtonEventsTest.java
  tests/system/src/test/java/test/robot/com/sun/glass/ui/monocle/RobotTest.java
  tests/system/src/test/java/test/robot/javafx/scene/RobotTest.java
Labels: enhancement

#318 Fix toolbar overflow (JDK-8152395)
  modules/javafx.controls/src/main/java/javafx/scene/control/skin/ToolBarSkin.java
  modules/javafx.controls/src/test/java/test/javafx/scene/control/ToolbarTest.java
Labels: bug

#272 JDK-8088418: Reintroduce JFR Pulse Logger
  modules/javafx.base/src/main/java/com/sun/javafx/logging/PrintLogger.java
  modules/javafx.base/src/main/java/com/sun/javafx/logging/PulseLogger.java
  modules/javafx.base/src/main/java/com/sun/javafx/logging/jfr/JFRInputEvent.java
  modules/javafx.base/src/main/java/com/sun/javafx/logging/jfr/JFRPulseLogger.java
  modules/javafx.base/src/main/java/com/sun/javafx/logging/jfr/JFRPulsePhaseEvent.java
  modules/javafx.base/src/main/java/com/sun/javafx/logging/jfr/PulseId.java
  modules/javafx.base/src/main/java/module-info.java
Labels: enhancement

#343 JDK-8216470: Some methods of System.Logger are unimplemented in PlatformLogger
  modules/javafx.base/src/main/java/com/sun/javafx/logging/PlatformLogger.java
Labels: bug, regression

#345 JDK-8215435: Warn on usage of trampolines with gcc
  buildSrc/linux.gradle
  modules/javafx.media/src/main/native/gstreamer/projects/linux/avplugin/Makefile
  modules/javafx.media/src/main/native/gstreamer/projects/linux/fxplugins/Makefile
  modules/javafx.media/src/main/native/gstreamer/projects/linux/gstreamer-lite/Makefile
  modules/javafx.media/src/main/native/jfxmedia/projects/linux/Makefile
Labels: bug, build

#337 JDK-8215799: Complex text is not rendered by webkit on Windows
  modules/javafx.graphics/src/main/java/com/sun/javafx/font/CompositeGlyphMapper.java
  modules/javafx.web/src/main/java/com/sun/javafx/webkit/prism/WCFontImpl.java
  modules/javafx.web/src/main/native/Source/WebCore/platform/graphics/java/ComplexTextControllerJava.cpp
Labels: bug, regression

#342 JDK-8216377: Fix memoryleak for initial nodes of Window
  modules/javafx.graphics/src/main/java/javafx/scene/Node.java
  tests/system/src/test/java/test/javafx/scene/InitialNodesMemoryLeakTest.java
Labels: bug, regression

#125 JDK-8207839: [win] Negative glyph_id causes ArrayIndexOutOfBoundsException
  modules/javafx.graphics/src/main/java/com/sun/javafx/font/directwrite/DWGlyph.java
  modules/javafx.graphics/src/main/java/com/sun/javafx/font/directwrite/DWGlyphLayout.java
  tests/manual/text/BigGlyphIDTest.java
  tests/manual/text/BigGlyphIDTest_Expected.png
Labels: bug

#355 JDK-8213806: WebView - JVM crashes for given HTML
  modules/javafx.web/src/main/native/Source/WebCore/platform/URLHash.h
  modules/javafx.web/src/test/java/test/javafx/scene/web/MiscellaneousTest.java
Labels: bug, crash, regression

#353 JDK-8205092: Added dirty check for viewOrderChildren
  modules/javafx.graphics/src/main/java/javafx/scene/Parent.java
  modules/javafx.graphics/src/test/java/test/javafx/scene/ParentTest.java
Labels: bug

#346 JDK-8217333: Pass additional arguments to gradle from build.ps1
  tools/scripts/build.ps1
Labels: enhancement
