Repository javafxports/openjdk-jfx, pull requests merged in 2019-06, with the labels that each got.

#473 JDK-8211302: DND does not work on GTK3
  modules/javafx.graphics/src/main/native-glass/gtk/glass_dnd.cpp
  modules/javafx.graphics/src/main/native-glass/gtk/glass_dnd.h
  modules/javafx.graphics/src/main/native-glass/gtk/glass_general.cpp
  modules/javafx.graphics/src/main/native-glass/gtk/glass_general.h
  tests/manual/dnd/DndTest.java
Labels: bug

#460 JDK-8197536: TableView, ListView: unexpected scrolling behaviour on up/down keys
  modules/javafx.controls/src/main/java/javafx/scene/control/skin/VirtualFlow.java
  modules/javafx.controls/src/shims/java/javafx/scene/control/skin/VirtualFlowShim.java
  modules/javafx.controls/src/test/java/test/javafx/scene/control/skin/VirtualFlowTest.java
Labels: bug

#503 JDK-8226274: NPE in WinWindow.notifyMoving when Stage with no Scene is shown on 2nd monitor
  modules/javafx.graphics/src/main/java/com/sun/glass/ui/win/WinWindow.java
  tests/system/src/test/java/test/javafx/stage/MultipleScreensTest.java
Labels: bug

#413 JDK-8221269: Extract embedded actions from JSL grammar file to Visitor class
  build.gradle
  modules/javafx.graphics/src/jslc/antlr/com/sun/scenario/effect/compiler/JSL.g4
  modules/javafx.graphics/src/jslc/java/com/sun/scenario/effect/compiler/JSLC.java
  modules/javafx.graphics/src/jslc/java/com/sun/scenario/effect/compiler/backend/hw/ES2Backend.java
  modules/javafx.graphics/src/jslc/java/com/sun/scenario/effect/compiler/backend/hw/GLSLBackend.java
  modules/javafx.graphics/src/jslc/java/com/sun/scenario/effect/compiler/backend/hw/HLSLBackend.java
  modules/javafx.graphics/src/jslc/java/com/sun/scenario/effect/compiler/backend/hw/SLBackend.java
  modules/javafx.graphics/src/jslc/java/com/sun/scenario/effect/compiler/backend/prism/PrismBackend.java
  modules/javafx.graphics/src/jslc/java/com/sun/scenario/effect/compiler/backend/sw/java/JSWBackend.java
  modules/javafx.graphics/src/jslc/java/com/sun/scenario/effect/compiler/backend/sw/me/MEBackend.java
  modules/javafx.graphics/src/jslc/java/com/sun/scenario/effect/compiler/backend/sw/sse/SSEBackend.java
  modules/javafx.graphics/src/jslc/java/com/sun/scenario/effect/compiler/tree/CallExpr.java
  modules/javafx.graphics/src/jslc/java/com/sun/scenario/effect/compiler/tree/JSLVisitor.java
  modules/javafx.graphics/src/main/jsl-prism/CompileJSL.java
  modules/javafx.graphics/src/test/jslc/com/sun/scenario/effect/compiler/parser/AddExprTest.java
  modules/javafx.graphics/src/test/jslc/com/sun/scenario/effect/compiler/parser/AssignmentExprTest.java
  modules/javafx.graphics/src/test/jslc/com/sun/scenario/effect/compiler/parser/EqualityExprTest.java
  modules/javafx.graphics/src/test/jslc/com/sun/scenario/effect/compiler/parser/ExternalDeclarationTest.java
  modules/javafx.graphics/src/test/jslc/com/sun/scenario/effect/compiler/parser/FieldSelectTest.java
  modules/javafx.graphics/src/test/jslc/com/sun/scenario/effect/compiler/parser/FullySpecifiedTypeTest.java
  modules/javafx.graphics/src/test/jslc/com/sun/scenario/effect/compiler/parser/IterationStatementTest.java
  modules/javafx.graphics/src/test/jslc/com/sun/scenario/effect/compiler/parser/JumpStatementTest.java
  modules/javafx.graphics/src/test/jslc/com/sun/scenario/effect/compiler/parser/MultExprTest.java
  modules/javafx.graphics/src/test/jslc/com/sun/scenario/effect/compiler/parser/ParserBase.java
  modules/javafx.graphics/src/test/jslc/com/sun/scenario/effect/compiler/parser/PrimaryExprTest.java
  modules/javafx.graphics/src/test/jslc/com/sun/scenario/effect/compiler/parser/RelationalExprTest.java
  modules/javafx.graphics/src/test/jslc/com/sun/scenario/effect/compiler/parser/SelectionStatementTest.java
  modules/javafx.graphics/src/test/jslc/com/sun/scenario/effect/compiler/parser/UnaryExprTest.java
Labels: enhancement

#506 JDK-8226537: gnome-shell crashes when closing a multi-level stage initOwner()
  modules/javafx.graphics/src/main/native-glass/gtk/glass_window.cpp
Labels: bug, crash
