Repository javafxports/openjdk-jfx, pull requests merged in 2019-05, with the labels that each got.

#456 JDK-8193502: Dialog height switches between correct and too small when showing and hiding one dialog repeatedly on Linux
  modules/javafx.graphics/src/main/native-glass/gtk/glass_window.cpp
  tests/system/src/test/java/test/robot/javafx/scene/dialog/DialogRepeatedShowHideTest.java
Labels: bug

#445 JDK-8220272: Window order is not correct when Modality.WINDOW_MODAL
  modules/javafx.graphics/src/main/native-glass/gtk/glass_window.cpp
  tests/system/src/test/java/test/robot/javafx/stage/CheckWindowOrderTest.java
Labels: bug

#398 8088717: Taskbar iconification of undecorated windows in Windows
  modules/javafx.graphics/src/main/java/com/sun/glass/ui/Window.java
  modules/javafx.graphics/src/main/java/com/sun/javafx/tk/quantum/WindowStage.java
  modules/javafx.graphics/src/main/native-glass/win/GlassWindow.cpp
Labels: bug

#451 JDK-8210973: Focus goes to wrong Window when dismissing an Alert
  modules/javafx.graphics/src/main/java/com/sun/javafx/tk/quantum/WindowStage.java
  tests/system/src/test/java/test/robot/javafx/stage/FocusParentWindowOnChildCloseTest.java
Labels: bug

#467 Add SANDBOX-FILES.md to list the set of "sandbox-only" files.
  SANDBOX-FILES.md
Labels: documentation

#474 JDK-8222788: javafx.web build fails on XCode 10.2
  modules/javafx.web/src/main/native/Source/WTF/wtf/Optional.h
Labels: build

#468 JDK-8223377: JavaFX can crash due to loading the wrong native libraries if system libraries are installed
  modules/javafx.graphics/src/main/java/com/sun/glass/utils/NativeLibLoader.java
Labels: bug

#397 8089986: Removed beeping when alt+key is pressed on Windows
  modules/javafx.graphics/src/main/native-glass/win/GlassWindow.cpp
Labels: bug

#459 JDK-8222883: Ensemble: Update version of Lucene to 7.7.1
  apps/samples/.classpath
  apps/samples/Ensemble8/UPDATING-lucene.txt
  apps/samples/Ensemble8/build.gradle
  apps/samples/Ensemble8/build.xml
  apps/samples/Ensemble8/legal/lucene.md
  apps/samples/Ensemble8/nbproject/project.properties
  apps/samples/Ensemble8/src/generated/resources/ensemble/search/index/_0.cfe
  apps/samples/Ensemble8/src/generated/resources/ensemble/search/index/_0.cfs
  apps/samples/Ensemble8/src/generated/resources/ensemble/search/index/_0.si
  apps/samples/Ensemble8/src/generated/resources/ensemble/search/index/listAll.txt
  apps/samples/Ensemble8/src/generated/resources/ensemble/search/index/segments_1
  build.gradle
Labels: 3rdparty-upgrade
