Repository javafxports/openjdk-jfx, pull requests merged in 2019-07, with the labels that each got.

#523 JDK-8226365: Change JavaFX release version to 14
  build.properties
  modules/javafx.base/src/test/java/test/com/sun/javafx/runtime/VersionInfoTest.java
Labels: build

#524 JDK-8222912: Websocket client doesn't work in WebView
  modules/javafx.web/src/main/native/Source/WebCore/Sources.txt
  modules/javafx.web/src/main/native/Source/WebCore/platform/network/NetworkStorageSession.h
  modules/javafx.web/src/main/native/Source/WebCore/platform/network/java/NetworkStorageSessionJava.cpp
  modules/javafx.web/src/main/native/Source/WebCore/platform/network/java/SocketStreamHandleImpl.h
  modules/javafx.web/src/main/native/Source/WebCore/platform/network/java/SocketStreamHandleImplJava.cpp
  modules/javafx.web/src/main/native/Source/WebKitLegacy/PlatformJava.cmake
  modules/javafx.web/src/main/native/Source/WebKitLegacy/java/WebCoreSupport/FrameNetworkingContextJava.h
Labels: bug

#517 8185937: Editable Spinner up/down keys do not increment/decrement
  modules/javafx.controls/src/main/java/com/sun/javafx/scene/control/behavior/SpinnerBehavior.java
  modules/javafx.controls/src/main/java/javafx/scene/control/skin/SpinnerSkin.java
  modules/javafx.controls/src/test/java/test/javafx/scene/control/SpinnerTest.java
Labels: bug

#527 JDK-8193911: Create README file to document bumping the version number
  UPDATING-VERSION.md
Labels: documentation

#479 JDK-8224636: CSS "pointer-events" property "stroke" is not respected for SVG renderings
  modules/javafx.web/src/main/java/com/sun/javafx/webkit/prism/WCPathImpl.java
  modules/javafx.web/src/main/java/com/sun/webkit/graphics/WCPath.java
  modules/javafx.web/src/main/native/Source/WebCore/platform/graphics/DashArray.h
  modules/javafx.web/src/main/native/Source/WebCore/platform/graphics/java/GraphicsContextJava.cpp
  modules/javafx.web/src/main/native/Source/WebCore/platform/graphics/java/PathJava.cpp
  modules/javafx.web/src/main/native/Source/WebCore/platform/graphics/java/PlatformContextJava.h
  modules/javafx.web/src/test/java/test/javafx/scene/web/SVGPointerEventsTest.java
  modules/javafx.web/src/test/resources/test/html/pointerevents-stroke.html
Labels: bug

#526 JDK-8227540: Add README.md and CONTRIBUTING.md to jfx repo
  CONTRIBUTING.md
  README.md
Labels: documentation

#531 Update .github copy of README.md and CONTRIBUTING.md
  .github/CONTRIBUTING.md
  .github/README.md
Labels: documentation

#535 JDK-8223722: Cleanup .gitignore file
  .gitignore
Labels: housekeeping

#533 8209086: Some javafx.web files are missing GPLv2+Classpath copyright header
  modules/javafx.web/src/main/native/Source/WTF/wtf/java/DbgUtils.h
  modules/javafx.web/src/main/native/Source/WTF/wtf/java/MainThreadJava.cpp
  modules/javafx.web/src/main/native/Source/WTF/wtf/java/RunLoopJava.cpp
  modules/javafx.web/src/main/native/Source/WTF/wtf/java/StringJava.cpp
  modules/javafx.web/src/main/native/Source/WTF/wtf/java/TextBreakIteratorInternalICUJava.cpp
  modules/javafx.web/src/main/native/Source/WTF/wtf/unicode/java/UnicodeJava.cpp
  modules/javafx.web/src/main/native/Source/WTF/wtf/unicode/java/UnicodeJava.h
  modules/javafx.web/src/main/native/Source/WTF/wtf/unicode/java/mirrorPairs.h
  modules/javafx.web/src/main/native/Source/WebCore/PAL/pal/system/java/SoundJava.cpp
  modules/javafx.web/src/main/native/Source/WebCore/bridge/jni/jsc/BridgeUtils.h
  modules/javafx.web/src/main/native/Source/WebCore/editing/java/EditorJava.cpp
  modules/javafx.web/src/main/native/Source/WebCore/page/java/DragControllerJava.cpp
  modules/javafx.web/src/main/native/Source/WebCore/page/java/EventHandlerJava.cpp
  modules/javafx.web/src/main/native/Source/WebCore/page/java/FrameJava.cpp
  modules/javafx.web/src/main/native/Source/WebCore/platform/network/java/ResourceHandleJava.cpp
  modules/javafx.web/src/main/native/Source/WebCore/platform/network/java/ResourceRequestJava.cpp
  modules/javafx.web/src/main/native/Source/WebCore/platform/network/java/SynchronousLoaderClientJava.cpp
  modules/javafx.web/src/main/native/Source/WebCore/platform/network/java/URLLoader.h
  modules/javafx.web/src/main/native/Source/WebCore/plugins/java/PluginDataJava.cpp
  modules/javafx.web/src/main/native/Source/WebCore/plugins/java/PluginDataJava.h
  modules/javafx.web/src/main/native/Tools/DumpRenderTree/java/EventSender.cpp
  modules/javafx.web/src/main/native/Tools/DumpRenderTree/java/EventSender.h
  modules/javafx.web/src/main/native/Tools/DumpRenderTree/java/GCControllerJava.cpp
  modules/javafx.web/src/main/native/Tools/DumpRenderTree/java/JavaEnv.cpp
  modules/javafx.web/src/main/native/Tools/DumpRenderTree/java/JavaEnv.h
  modules/javafx.web/src/main/native/Tools/DumpRenderTree/java/TestRunnerJava.cpp
  modules/javafx.web/src/main/native/Tools/DumpRenderTree/java/WorkQueueItemJava.cpp
Labels: bug

#518 JDK-8227367 Add missing @Override's and fix static usage.
  modules/javafx.graphics/src/main/java/com/sun/prism/d3d/D3DContext.java
  modules/javafx.graphics/src/main/java/com/sun/prism/d3d/D3DGraphics.java
  modules/javafx.graphics/src/main/java/com/sun/prism/d3d/D3DMesh.java
  modules/javafx.graphics/src/main/java/com/sun/prism/d3d/D3DMeshView.java
  modules/javafx.graphics/src/main/java/com/sun/prism/d3d/D3DPhongMaterial.java
  modules/javafx.graphics/src/main/java/com/sun/prism/d3d/D3DPipeline.java
  modules/javafx.graphics/src/main/java/com/sun/prism/d3d/D3DRTTexture.java
  modules/javafx.graphics/src/main/java/com/sun/prism/d3d/D3DResource.java
  modules/javafx.graphics/src/main/java/com/sun/prism/d3d/D3DResourceFactory.java
  modules/javafx.graphics/src/main/java/com/sun/prism/d3d/D3DShader.java
  modules/javafx.graphics/src/main/java/com/sun/prism/d3d/D3DSwapChain.java
  modules/javafx.graphics/src/main/java/com/sun/prism/d3d/D3DTexture.java
  modules/javafx.graphics/src/main/java/com/sun/prism/es2/ES2Graphics.java
  modules/javafx.graphics/src/main/java/com/sun/prism/es2/ES2Mesh.java
  modules/javafx.graphics/src/main/java/com/sun/prism/es2/ES2MeshView.java
  modules/javafx.graphics/src/main/java/com/sun/prism/es2/ES2PhongMaterial.java
  modules/javafx.graphics/src/main/java/com/sun/prism/es2/ES2RTTexture.java
  modules/javafx.graphics/src/main/java/com/sun/prism/es2/ES2ResourceFactory.java
  modules/javafx.graphics/src/main/java/com/sun/prism/es2/ES2Shader.java
  modules/javafx.graphics/src/main/java/com/sun/prism/es2/ES2SwapChain.java
  modules/javafx.graphics/src/main/java/com/sun/prism/es2/ES2Texture.java
  modules/javafx.graphics/src/main/java/com/sun/prism/es2/ES2TextureData.java
  modules/javafx.graphics/src/main/java/com/sun/prism/es2/GLFactory.java
  modules/javafx.graphics/src/main/java/com/sun/prism/es2/GLPixelFormat.java
Labels: bug

#472 JDK-8167148 : Add native rendering support by supporting WritableImages backed by NIO ByteBuffers
  modules/javafx.graphics/src/main/java/com/sun/javafx/tk/PlatformImage.java
  modules/javafx.graphics/src/main/java/com/sun/javafx/tk/quantum/QuantumToolkit.java
  modules/javafx.graphics/src/main/java/com/sun/prism/Image.java
  modules/javafx.graphics/src/main/java/com/sun/prism/impl/BaseResourceFactory.java
  modules/javafx.graphics/src/main/java/javafx/scene/image/Image.java
  modules/javafx.graphics/src/main/java/javafx/scene/image/PixelBuffer.java
  modules/javafx.graphics/src/main/java/javafx/scene/image/WritableImage.java
  modules/javafx.graphics/src/main/native-prism-d3d/D3DResourceFactory.cc
  modules/javafx.graphics/src/test/java/test/com/sun/javafx/pgstub/StubPlatformImage.java
  modules/javafx.graphics/src/test/java/test/com/sun/javafx/pgstub/StubWritablePlatformImage.java
  modules/javafx.graphics/src/test/java/test/javafx/scene/image/PixelBufferTest.java
  tests/manual/graphics/ByteBgraPrePixelBufferPerformanceTest.java
  tests/manual/graphics/IntArgbPrePixelBufferPerformanceTest.java
  tests/system/src/test/java/test/robot/javafx/scene/PixelBufferDrawTest.java
Labels: enhancement

#545 JDK-8227431: [Windows] Fix assertion failure on X86 32-bit when enabling CLOOP based JavaScript interpreter
  modules/javafx.web/src/main/native/Source/JavaScriptCore/llint/LLIntData.h
  modules/javafx.web/src/main/native/Source/WebCore/bindings/js/CommonVM.cpp
Labels: bug, regression
