Repository javafxports/openjdk-jfx, pull requests merged in 2019-08, with the labels that each got.

#543 JDK-8228766: [Mac] fix deadlock in platform.startup(Runnable r)
  modules/javafx.graphics/src/main/java/javafx/application/Platform.java
  modules/javafx.graphics/src/main/native-glass/mac/GlassApplication.m
  tests/system/src/test/java/test/com/sun/javafx/application/ConcurrentStartupTest.java
  tests/system/src/test/java/test/com/sun/javafx/application/StaticStartupTest.java
Labels: bug

#550 JDK-8220396: Bindings class gives a lot of unneeded 'select-binding' log messages
  modules/javafx.base/src/main/java/com/sun/javafx/binding/SelectBinding.java
Labels: bug

#555 JDK-8229328: [windows] PlatformFileHandle type should be JGObject rather than void*
  modules/javafx.web/src/main/native/Source/WTF/wtf/FileSystem.h
Labels: bug, regression

#559 Fix line endings, non-ASCII characters in CI scripts
  .travis.yml
  appveyor.yml
Labels: build

#544 JDK-8179097: Fix NPE on removing mnemonics of disposed popup
  modules/javafx.controls/src/main/java/com/sun/javafx/scene/control/skin/Utils.java
  modules/javafx.controls/src/main/java/javafx/scene/control/skin/MenuButtonSkinBase.java
  tests/system/src/test/java/test/javafx/scene/control/MenuButtonSkinBaseNPETest.java
Labels: bug

#520 JDK-8227366: Wrong stage gets focused after modal stage creation
  modules/javafx.graphics/src/main/java/com/sun/javafx/tk/quantum/WindowStage.java
Labels: bug

#576 JDK-8230361: [web] Cookies are not enabled in WebKit v608.1
  modules/javafx.web/src/main/native/Source/WebKitLegacy/java/WebCoreSupport/WebPage.cpp
  modules/javafx.web/src/test/java/test/javafx/scene/web/MiscellaneousTest.java
Labels: bug, regression
