Repository javafxports/openjdk-jfx, pull requests merged in 2019-02, with the labels that each got.

#373 JDK-8218611: [DRT] fast/xslt tests fails with Unsupported encoding windows-1251
  modules/javafx.web/src/main/native/Source/ThirdParty/libxml/mac/include/libxml/xmlversion.h
  modules/javafx.web/src/test/java/test/javafx/scene/web/MiscellaneousTest.java
Labels: bug, regression

#378 JDK-8219008: Update OpenGL Headers to version 4.6
  modules/javafx.graphics/src/main/legal/opengl_fx.md
  modules/javafx.graphics/src/main/native-prism-es2/GL/glext.h
  modules/javafx.graphics/src/main/native-prism-es2/GL/glx.h
  modules/javafx.graphics/src/main/native-prism-es2/GL/glxext.h
  modules/javafx.graphics/src/main/native-prism-es2/GL/wglext.h
  modules/javafx.graphics/src/main/native-prism-es2/KHR/khrplatform.h
Labels: 3rdparty-upgrade

#349 JDK-8215775: Scrollbars from web pages appear to be absolute, overlapping everything
  modules/javafx.web/src/main/native/Source/WebCore/SourcesPlatformJava.txt
  modules/javafx.web/src/main/native/Source/WebCore/platform/graphics/java/ComplexTextControllerJava.cpp
  modules/javafx.web/src/main/native/Source/WebCore/platform/java/ScrollAnimatorJava.cpp
  modules/javafx.web/src/main/native/Source/WebCore/platform/java/ScrollAnimatorJava.h
  modules/javafx.web/src/main/native/Source/WebCore/platform/java/ScrollbarThemeJava.cpp
  modules/javafx.web/src/main/native/Source/WebCore/platform/java/ScrollbarThemeJava.h
Labels: bug, regression

#357 JDK-8217492: memory leak after the event WindowEvent.DESTROY
  modules/javafx.graphics/src/main/java/com/sun/javafx/tk/quantum/WindowStage.java
Labels: bug
