Repository javafxports/openjdk-jfx, pull requests merged in 2019-03, with the labels that each got.

#390 JDK-8219734: [WebView] Get rid of macOS SDK private API usage
  modules/javafx.web/src/main/native/Source/WTF/wtf/BlockPtr.h
  modules/javafx.web/src/main/native/Source/WTF/wtf/CMakeLists.txt
  modules/javafx.web/src/main/native/Source/WTF/wtf/RandomDevice.cpp
  modules/javafx.web/src/main/native/Source/WTF/wtf/spi/darwin/CommonCryptoSPI.h
  modules/javafx.web/src/main/native/Source/WebCore/crypto/CommonCryptoUtilities.h
  modules/javafx.web/src/main/native/Source/WebCore/page/Crypto.cpp
  modules/javafx.web/src/main/native/Source/bmalloc/bmalloc/CryptoRandom.cpp
Labels: bug

#399 JDK-8220147: Cherry pick GTK WebKit 2.22.7 changes
  modules/javafx.web/src/main/native/Source/JavaScriptCore/bytecode/CodeBlock.cpp
  modules/javafx.web/src/main/native/Source/JavaScriptCore/dfg/DFGAbstractInterpreterInlines.h
  modules/javafx.web/src/main/native/Source/JavaScriptCore/dfg/DFGArgumentsEliminationPhase.cpp
  modules/javafx.web/src/main/native/Source/JavaScriptCore/dfg/DFGByteCodeParser.cpp
  modules/javafx.web/src/main/native/Source/JavaScriptCore/dfg/DFGClobberize.h
  modules/javafx.web/src/main/native/Source/JavaScriptCore/dfg/DFGCommonData.cpp
  modules/javafx.web/src/main/native/Source/JavaScriptCore/dfg/DFGCommonData.h
  modules/javafx.web/src/main/native/Source/JavaScriptCore/dfg/DFGConstantFoldingPhase.cpp
  modules/javafx.web/src/main/native/Source/JavaScriptCore/dfg/DFGDoesGC.cpp
  modules/javafx.web/src/main/native/Source/JavaScriptCore/dfg/DFGFixupPhase.cpp
  modules/javafx.web/src/main/native/Source/JavaScriptCore/dfg/DFGIntegerCheckCombiningPhase.cpp
  modules/javafx.web/src/main/native/Source/JavaScriptCore/dfg/DFGIntegerRangeOptimizationPhase.cpp
  modules/javafx.web/src/main/native/Source/JavaScriptCore/dfg/DFGNodeType.h
  modules/javafx.web/src/main/native/Source/JavaScriptCore/dfg/DFGSSALoweringPhase.cpp
  modules/javafx.web/src/main/native/Source/JavaScriptCore/dfg/DFGSpeculativeJIT.cpp
  modules/javafx.web/src/main/native/Source/JavaScriptCore/ftl/FTLLowerDFGToB3.cpp
  modules/javafx.web/src/main/native/Source/JavaScriptCore/runtime/SamplingProfiler.cpp
  modules/javafx.web/src/main/native/Source/JavaScriptCore/runtime/TypeSet.cpp
  modules/javafx.web/src/main/native/Source/JavaScriptCore/yarr/YarrJIT.cpp
  modules/javafx.web/src/main/native/Source/WebCore/accessibility/AXObjectCache.cpp
  modules/javafx.web/src/main/native/Source/WebCore/accessibility/AXObjectCache.h
  modules/javafx.web/src/main/native/Source/WebCore/accessibility/AccessibilityObject.cpp
  modules/javafx.web/src/main/native/Source/WebCore/dom/Document.h
  modules/javafx.web/src/main/native/Source/WebCore/html/HTMLPlugInElement.cpp
  modules/javafx.web/src/main/native/Source/WebCore/loader/DocumentLoader.cpp
  modules/javafx.web/src/main/native/Source/WebCore/loader/DocumentLoader.h
  modules/javafx.web/src/main/native/Source/WebCore/loader/FrameLoadRequest.h
  modules/javafx.web/src/main/native/Source/WebCore/loader/FrameLoader.cpp
  modules/javafx.web/src/main/native/Source/WebCore/loader/FrameLoader.h
  modules/javafx.web/src/main/native/Source/WebCore/page/DOMTimer.cpp
  modules/javafx.web/src/main/native/Source/WebCore/page/DragController.cpp
  modules/javafx.web/src/main/native/Source/WebCore/platform/ThreadTimers.cpp
  modules/javafx.web/src/main/native/Source/WebCore/platform/ThreadTimers.h
  modules/javafx.web/src/main/native/Source/WebCore/platform/Timer.cpp
  modules/javafx.web/src/main/native/Source/WebCore/platform/Timer.h
  modules/javafx.web/src/main/native/Source/WebCore/testing/Internals.cpp
  modules/javafx.web/src/main/native/Source/WebCore/testing/Internals.h
  modules/javafx.web/src/main/native/Source/WebCore/testing/Internals.idl
Labels: 3rdparty-upgrade

#403 JDK-8220375: Fix IOS build issues #402
  buildSrc/ios.gradle
  modules/javafx.graphics/src/main/native-prism-es2/ios/IOSWindowSystemInterface.m
Labels: bug, build

#367 JDK-8201539: WICCreateImagingFactory: defer CoUninitialize() call to thread exit (dispose hook approach)
  modules/javafx.graphics/src/main/java/com/sun/javafx/font/directwrite/DWFactory.java
  modules/javafx.graphics/src/main/java/com/sun/javafx/font/directwrite/OS.java
  modules/javafx.graphics/src/main/java/com/sun/prism/GraphicsPipeline.java
  modules/javafx.graphics/src/main/native-font/directwrite.cpp
Labels: bug

#137 JDK-8208076 : display INVISIBLE_GLYPH_ID as square box on Windows
  modules/javafx.graphics/src/main/java/com/sun/prism/sw/SWGraphics.java
  tests/manual/text/INVISIBLE_GLYPH_IDTest.java
  tests/manual/text/INVISIBLE_GLYPH_IDTest_Expected.png
Labels: bug

#407 JDK-8208173: isComplexCharCode() returns false for U+11FF
  modules/javafx.graphics/src/main/java/com/sun/javafx/text/ScriptMapper.java
Labels: bug

#392 JDK-8219917: [WebView] Sub-resource integrity check fails
  modules/javafx.web/src/main/java/com/sun/javafx/webkit/WCMessageDigestImpl.java
  modules/javafx.web/src/main/java/com/sun/webkit/perf/WCMessageDigestPerfLogger.java
  modules/javafx.web/src/main/java/com/sun/webkit/security/WCMessageDigest.java
  modules/javafx.web/src/main/native/Source/WebCore/PAL/pal/PlatformJava.cmake
  modules/javafx.web/src/main/native/Source/WebCore/PAL/pal/crypto/java/CryptoDigestJava.cpp
  modules/javafx.web/src/test/java/test/javafx/scene/web/SubresourceIntegrityTest.java
  modules/javafx.web/src/test/resources/test/html/subresource-integrity-test.js
Labels: bug

#410 Update boot JDK to 12
  .travis.yml
  appveyor.yml
Labels: build

#420 JDK-8210508: Update JDK_DOCS property to point to JDK 12 docs
  build.gradle
Labels: build

#414 JDK-8215686: FX build fails using gradle 5
  build.gradle
  buildSrc/src/main/groovy/com/sun/javafx/gradle/NativeCompileTask.groovy
  settings.gradle
Labels: bug, build
